name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t simple-time-service .

      - name: Tag Docker image
        run: |
          docker tag simple-time-service ${{ secrets.DOCKERHUB_USERNAME }}/simple-time-service:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-time-service:latest

  deploy-terraform:
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # Ensure Docker image is built first
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your preferred region

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Plan Terraform changes
        run: |
          cd terraform
          terraform plan

      - name: Apply Terraform changes
        run: |
          cd terraform
          terraform apply -auto-approve